# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tech Musings
tagline:             'Tech and other stuff'
description:         'Mostly note to self'
url:                 http://pandiaraj.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Pandiaraj
  url:               https://twitter.com/npandiaraj
  email:             pandiaraj+blog@gmail.com

# Custom vars
version:             1.0.0

# Archive/About pages
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
