# Site settings
title: My Blog
email: pandiaraj AT gmail
description: "Learning notes"
baseurl: ""
url: "http://pandiaraj.com"
github: pandiaraj
twitter: npandiaraj

# Build settings
markdown: kramdown
permalink: pretty
